### ISSUE TITLE
Study References not updating in Search filter

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#1992]
![Screenshot_2020-03-24 FBIS SASS(1)](https://user-images.githubusercontent.com/45286876/77420977-b034d180-6dd3-11ea-8e32-84c6a969baaa.png)

SASS data has been added to live site - as above.

Study reference is not showing in the Ollis

![Screenshot_2020-03-24 FBIS Map](https://user-images.githubusercontent.com/45286876/77421105-e2463380-6dd3-11ea-9a8b-14b400330b20.png)

**Comment by dimasciput** [comment]
@helendallas currently it only filter by peer-reviewed reference and database, I will update it to include published report data.

**Comment by dimasciput** [comment]
![image](https://user-images.githubusercontent.com/1979569/78116356-5ca73100-742e-11ea-84e8-8d1f934f23cb.png)


Fixed in testing

**Comment by helendallas** [comment]
@dimasciput 
This is great thanks, I am closing ticket

**Comment by helendallas** [comment]
@dimasciput 
Reports and theses are not showing in the testing site after ingestion of the invertebrate data. I am reopening this issue

**Comment by dimasciput** [comment]
@helendallas please check testing again

**Comment by helendallas** [comment]
@dimasciput 
Still not visible. e.g.

Bellingan   TA | 2010

![image](https://user-images.githubusercontent.com/45286876/80461617-d51de680-8935-11ea-8fe8-f97d5bd95e79.png)

Others
Thesis: Shelton 2013
Report: Snaddon K, Ractliffe G & Ewart-Smith J | 2014
Thesis: Stevens DM | 2008

**Comment by dimasciput** [comment]
@helendallas yes currently you can only search the report title for thesis and published report. Let me add the author's name

**Comment by dimasciput** [comment]
@helendallas please can you check again? 

> Report: Snaddon K, Ractliffe G & Ewart-Smith J | 2014

For this report, only first owner will be displayed on the site.

**Comment by helendallas** [comment]
Checked, but still not visible on testing

**Comment by dimasciput** [comment]
![image](https://user-images.githubusercontent.com/1979569/80467707-6a39d300-8968-11ea-8dd1-73ec3aac65c9.png)
it's there, maybe try refresh your browser

**Comment by dimasciput** [comment]
@helendallas

**Comment by helendallas** [comment]
@dimasciput Study References from ingested invertebrate data not showing - please can you check why. it as working before.

E.g Scodanibbio L
Tharme RE etc

**Comment by dimasciput** [comment]
@helendallas checking

**Comment by dimasciput** [comment]
@helendallas fixed, please try again

**Comment by helendallas** [comment]
@dimasciput Working now thanks
