### ISSUE TITLE
FILTERS & LAYERS (V4 testing)

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#2052]
@NyakudyaA we have created a [spreadsheet on dropbox](https://www.dropbox.com/s/i6qizh1igvhb8hl/Layers%20Infomation%20to%20Display.xlsx?dl=0) with the information that needs to be displayed for each layer. 
- In some cases field labels need renaming if possible? (we have indicated this in the comments column)
- We have indicated which layers can be turned off for now
- NBA 2018 layers are not on the layer selector yet?

@dimasciput 
**Here is a list of other spatial filter issues needing fixing**

1. Please capitalise all filter names. There is currently a mix of upper and lower case letters. 
<img width="281" alt="Screenshot 2020-04-22 at 09 36 34" src="https://user-images.githubusercontent.com/44292029/79953936-ea4dcd80-847c-11ea-92b3-4656f9fb02cd.png">

2. Search/reset bar disappears from view if too many tabs open. Can we pin to top and have it always showing? We have discussed this in a previous zoom and decided it’s a good idea. 

3. 3rd party data tab (including miniSASS and flow stations) still not implemented.

4. Red outlines lines showing for some but not all filters #1698 

5. Management Area
- River Management Unit (RMU) still needs to be added #1856 
<img width="125" alt="image" src="https://user-images.githubusercontent.com/44292029/79954776-19b10a00-847e-11ea-97b1-0d4b49c7abfc.png">

6. Critical Biodiversity Areas (CBA) 
- Needs some text refinement:
<img width="451" alt="image" src="https://user-images.githubusercontent.com/44292029/79955815-9a243a80-847f-11ea-9e66-eadd2520f9a3.png">
 
- Ecological Support Areas (ESA): @NyakudyaA (1) should there not be more categories within the ESA drawer, (2) map does not load when I select this layer?
- National Protected Areas (PA): blank category needs to be deleted
<img width="214" alt="image" src="https://user-images.githubusercontent.com/44292029/79956204-1e76bd80-8480-11ea-998c-f8e0c79dd982.png">

- Critical Biodiversity Area (CBA): Provincial - Western Cape is missing

<img width="370" alt="image" src="https://user-images.githubusercontent.com/44292029/79956518-8a592600-8480-11ea-8395-322ca76d9dbc.png">

7. National Freshwater Ecosystem Priority Areas (NFEPA)
- Change Area to ‘Areas’ in title
- See ticket #1934 for issues with fish sanctuaries.
<img width="258" alt="image" src="https://user-images.githubusercontent.com/44292029/79956776-e0c66480-8480-11ea-8368-cf41b0542d3b.png">

8. National Biodiversity Assessment (NBA)
- See ticket #1807 

9.  Geomorphological Zone 
- see ticket #2002 

**Layers**
- Layer selector: make the drawers thinner and remove the green lables and sliders
- see ticket #2050 

@helendallas @timlinux

**Comment by dimasciput** [comment]
- [x] Please capitalise all filter names. There is currently a mix of upper and lower case letters.

- [x] Search/reset bar disappears from view if too many tabs open. Can we pin to top and have it always showing? We have discussed this in a previous zoom and decided it’s a good idea.

- [x] 3rd party data tab (including miniSASS and flow stations) still not implemented.

- [x] Red outlines lines showing for some but not all filters - **Fixed in testing**

- [x] River Management Unit (RMU) still needs to be added - **Added in live site**

**Comment by jeremyshelton** [comment]
@dimasciput thanks for working through these tasks. These fixes look good, except for some filter red lines still not showing. Also, I have now thoroughly tested all filters and am happy to report that most are working well. I did find a few issues that need fixing - see issues with red and orange labels in [this filter testing spreadsheet](https://www.dropbox.com/s/yvi7p28yd0uhc2s/FBIS%20FILTER%20TESTING_MAY2020.xlsx?dl=0) on dropbox.

**Comment by jeremyshelton** [comment]
@NyakudyaA - please see request at the top of this ticket detailing layer information that should be included.

**Comment by NyakudyaA** [comment]
@jeremyshelton 
[Layers Infomation to Display.xlsx](https://github.com/kartoza/django-bims/files/4598562/Layers.Infomation.to.Display.xlsx)

Which layer is the `National Biodiversity Assessment (NBA) 2019` 

For the `Ecological Support Areas (ESA): National` I suggest we remove this layer in geocontext or using it for spatial filters because it doesn't have any useful attributes which we can use to do the filtering with. we should not be using `gid`  to identify the layer

**Comment by jeremyshelton** [comment]
@NyakudyaA 

Which layer is the National Biodiversity Assessment (NBA) 2019

**Error. That is supposed to be 2018. I have corrected it in the spreadsheet.** 

For the Ecological Support Areas (ESA): National I suggest we remove this layer in geocontext or using it for spatial filters because it doesn't have any useful attributes which we can use to do the filtering with. we should not be using gid to identify the layer

**OK, If I understand correctly, you are suggesting that we do not show any clickable info labels for this layer? If So, I think that is fine. We do want users to be able to filter all sites that fall within ESAs, so important to retain this layer as a filter.**  

@helendallas

**Comment by NyakudyaA** [comment]
> @NyakudyaA
> 
> Which layer is the National Biodiversity Assessment (NBA) 2019
> 
> **Error. That is supposed to be 2018. I have corrected it in the spreadsheet.**

Will look at it
> 
> For the Ecological Support Areas (ESA): National I suggest we remove this layer in geocontext or using it for spatial filters because it doesn't have any useful attributes which we can use to do the filtering with. we should not be using gid to identify the layer
> 
> **OK, If I understand correctly, you are suggesting that we do not show any clickable info labels for this layer? If So, I think that is fine. We do want users to be able to filter all sites that fall within ESAs, so important to retain this layer as a filter.**

We can filter but it is not usefull to filter using the gid. We need a column that is useful for them to be able to use as a filter. I am suggesting we remove it as a map layer and spatial filter unless we identify useful attributes
> 
> @helendallas

**Comment by jeremyshelton** [comment]
@NyakudyaA we just want to see the ESA layer and filter by the ESA layers - i.e. return only sites falling within these areas. 

Maybe best to chat about it at today's Zoom at 11h00?

@helendallas

**Comment by NyakudyaA** [comment]
> @NyakudyaA we just want to see the ESA layer and filter by the ESA layers - i.e. return only sites falling within these areas.
> 
> Maybe best to chat about it at today's Zoom at 11h00?
> 
> @helendallas

![gid-mview](https://user-images.githubusercontent.com/2510900/81787195-f8818d80-9500-11ea-9065-b8072b6aa14d.png)

Above are the subset of the attributes for the layer. In the other ticket, you mentioned it would be nice to only show the gid. The gid is a column that is generated to show that each row is unique. It has no relationship with the attributes.

How do you plan to filter based on this? To a normal user, this number means nothing

**Comment by jeremyshelton** [comment]
OK, @NyakudyaA can you join the zoom at 11h00?

**Comment by jeremyshelton** [comment]
@dimasciput there are still several outstanding filter issues that need to be addressed. These are listed in this spreadsheet in the Filters folder called FBIS FILTER TESTING. 

Here is a link to the file if you need one: https://www.dropbox.com/s/yvi7p28yd0uhc2s/FBIS%20FILTER%20TESTING_MAY2020.xlsx?dl=0

Outstanding issues are highlighted red in these two columns:
<img width="899" alt="Screenshot 2020-05-27 at 07 33 12" src="https://user-images.githubusercontent.com/44292029/82981589-aeaea200-9fec-11ea-953d-d7c8822c8343.png">

@helendallas @timlinux

**Comment by timlinux** [comment]
@jeremyshelton you can manage the labels for the spatial filters yourself here:

http://staging.freshwaterbiodiversity.org/admin/bims/locationcontextgroup/

Pop us a note if you need any help.

**Comment by jeremyshelton** [comment]
Thanks @timlinux 

@dimasciput and @NyakudyaA I have revised the spreadsheet a little - please focus on the red rows in the 'checked' column:

<img width="469" alt="Screenshot 2020-05-27 at 14 04 29" src="https://user-images.githubusercontent.com/44292029/83016972-197ad000-a023-11ea-85a1-390f167d5bd6.png">

**Comment by jeremyshelton** [comment]
Thanks @timlinux

I have fixed as many names as I can from there. 

@dimasciput and @NyakudyaA I have revised the spreadsheet a little - please focus on remaining issues indicated by the red rows in the 'checked' column:

<img width="455" alt="Screenshot 2020-05-27 at 14 33 22" src="https://user-images.githubusercontent.com/44292029/83019430-39ac8e00-a027-11ea-80d1-ef763d2ec3b1.png">

Thanks!

**Comment by jeremyshelton** [comment]
@dimasciput @NyakudyaA 
Here is a list of the filter issues that still need to be addressed. 

<img width="640" alt="Screenshot 2020-05-28 at 12 09 45" src="https://user-images.githubusercontent.com/44292029/83128908-5787fa80-a0dc-11ea-987c-934614b75d61.png">

**Comment by dimasciput** [comment]
@jeremyshelton yes I’m still fetching some data from geocontext, we can do this while the site is live.

**Comment by jeremyshelton** [comment]
Here is a link which contains the spreadsheet of outstanding spatial filter issues and associated url links. See sheet called 'oct2020':https://www.dropbox.com/home/FRC_Kartoza%20Shared%20Folder%20for%20FBIS/Filters?select=FBIS+FILTER+TESTING_MAY2020.xlsx

Also, here is s screenshot of the outstanding issues:

<img width="640" alt="Screenshot 2020-10-06 at 12 04 56" src="https://user-images.githubusercontent.com/44292029/95188202-638f7180-07cc-11eb-9d10-2d9172ab3507.png">

**Comment by dimasciput** [comment]
@jeremyshelton I couldn't find the file, can you send it to me via email instead?

**Comment by jeremyshelton** [comment]
Done.

**Comment by dimasciput** [comment]
@jeremyshelton I'll be running a script over the weekend to retrieve the missing geocontext data, I don't want to make the site unstable right now.

**Comment by jeremyshelton** [comment]
OK thanks @dimasciput 
Ping us when it's done and I'll have a look 👍

**Comment by helendallas** [comment]
@jeremyshelton Please can you go through this today Jeremy and highlight any issues not working.

**Comment by jeremyshelton** [comment]
@helendallas @dimasciput I will test this tonight or first thing tomorrow morning.

**Comment by jeremyshelton** [comment]
@dimasciput @helendallas I have re-tested all of the spatial filters and compiled an updated list of outstanding issues. Most of these are the same as those identified during the previous testing last month. The main issues are

1. Red outlines for filter selections have disappeared. 
2. Several of the CBA filters are not working properly or at all
3. National Biodiversity Assessment 2018 (NBA) filter category names often incorrect, and some filters not working properly. (correct filter category names are included in the separate sheet called 'nba2018)

Once again, I have updated the Excel spreadsheet with a detailed list of these issues. This is available on dropbox: FRC_Kartoza Shared Folder for FBIS > FILTERS

Here is a screen shot of the main issues from that spreadsheet:

<img width="1098" alt="Screenshot 2020-11-10 at 19 37 42" src="https://user-images.githubusercontent.com/44292029/98710589-86451500-238c-11eb-97c0-80977d6843d6.png">

**Comment by helendallas** [comment]
@dimasciput @jeremyshelton @NyakudyaA 
Thanks for the comprehensive testing Jeremy

Please see related ticket #1807 which was directed to Admire. NBA ccategories/details

**Comment by helendallas** [comment]
I have separated out this ticket into 3:
#2398 #2399 #2400
