### ISSUE TITLE
Error when uploading new source reference

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#2849]
I am getting an error message when uploading a new source reference. The doc is 20mb, but I cant reduce any more. I thought this issue had been resolved?

![image](https://user-images.githubusercontent.com/45286876/139453140-1b46573f-3b02-4677-8152-fcc30ae4bb3a.png)

![image](https://user-images.githubusercontent.com/45286876/139453155-171f546e-8628-4be4-82db-0d3ba9ef9016.png)

**Comment by dimasciput** [comment]
@helendallas can you send me the pdf file please?

**Comment by dimasciput** [comment]
@helendallas fixed in testing, please try it

**Comment by helendallas** [comment]
@dimasciput Same issue
![image](https://user-images.githubusercontent.com/45286876/144400972-095f3014-c4c6-444f-885d-b0eb362ff5cb.png)

**Comment by dimasciput** [comment]
@helendallas can you share a screenshot of the form before you click the submit button?

**Comment by helendallas** [comment]
here we go 
![image](https://user-images.githubusercontent.com/45286876/144410850-b6db6607-b79d-4e17-be60-d0eb31b66950.png)

**Comment by helendallas** [comment]
@dimasciput still getting error
![image](https://user-images.githubusercontent.com/45286876/144573865-ee1cd282-cba7-4b84-a0a7-a7b0b3700c2f.png)

**Comment by dimasciput** [comment]
@helendallas very weird, I can upload the file. Should I just create it myself for now?

**Comment by helendallas** [comment]
Yes please, and then I will close ticket and create a new one if the issue persists

**Comment by dimasciput** [comment]
@helendallas I added the source reference, will you update the title and the source please

live site : https://freshwaterbiodiversity.org/edit-source-reference/1112/?next=/source-references/%3F%26q%3Dupdate
testing : https://testing.healthyrivers.kartoza.com/edit-source-reference/1119/?next=/source-references/%3F%26q%3Dupdate

**Comment by helendallas** [comment]
Thanks @dimasciput Done Closing ticket

**Comment by helendallas** [comment]
@dim Reopening ticket as this source reference cannot be downloaded, so there is still an issue even though you uploaded it in the backend.

![image](https://user-images.githubusercontent.com/45286876/145185604-a6689ddd-b425-4ed3-8e5f-e293ab5d1e1f.png)

**Comment by dimasciput** [comment]
@helendallas this is fixed, you can now download the file.
