### ISSUE TITLE
CSV downloads: multiple issues (urgent)

### ISSUE THREAD

**Issue by jeremyshelton** [kartoza/django-bims#3141]
@dimasciput @helendallas @timlinux 

We have users engaging with the csv downloads and encountering problems. 

**Main issues summarised below:**
1. There are over 1000 columns with lots of column repeats (I think this issue is specific to Anuran data).
2. For GBIF & VM records there is no additional information coming through about the source from which the data originated. For example, no GBIF ID or VM number, no organisation or institution or person who uploaded the data. (this is an issue for both fish and anuran data). 

An example is this download of anuran data: https://freshwaterbiodiversity.org/uploaded/processed_csv/Josh_Weeber/09a4acb6e439a944bfd6a3b456cbdbdd4e50b37dcc0749d9c2fa501aecf6ecfc 

Issue 2 is also evident in this fish data download: https://freshwaterbiodiversity.org/uploaded/processed_csv/Jeremy_Shelton/446cd8494bd35714db427f26c0d3edf2fa0e68c7d9b6415fb062fdba67062e96

It is critical that key information about the record source comes through in the CSV. Importantly, we need to be able to see for GBIF data which institution + person the data came from, and also whether or not the data have come from iNaturalist. Similarly, for VM data we need to see who uploaded each record and what organisation they come from. 

I think that the columns are mostly there, but the problem is that they are not being populated.

This ticket has some overlap with #3089 and #3118 and #3115 and #3099

**Comment by dimasciput** [comment]
@Fanevanjanahary please can you check the first issue.

**Comment by Fanevanjanahary** [comment]
Hi @jeremyshelton please can you direct me from where did you download your CSV (issue 1)? I've tested from single site dashboard from Anura data and here is what I get [https://testing.healthyrivers.kartoza.com/uploaded/processed_csv/kartoza_admin/6c5f6852496b11e29bb1eb117b1b4d618e7468126f392985f1173d854be42d4e](https://testing.healthyrivers.kartoza.com/uploaded/processed_csv/kartoza_admin/6c5f6852496b11e29bb1eb117b1b4d618e7468126f392985f1173d854be42d4e) 
Thank you

**Comment by jeremyshelton** [comment]
@Fanevanjanahary https://freshwaterbiodiversity.org/uploaded/processed_csv/Josh_Weeber/09a4acb6e439a944bfd6a3b456cbdbdd4e50b37dcc0749d9c2fa501aecf6ecfc

**Comment by dimasciput** [comment]
@jeremyshelton I think what she meant was what the filters are in order to get this data.

**Comment by dimasciput** [comment]
@jeremyshelton @Fanevanjanahary actually you can see the filters here Faneva : https://freshwaterbiodiversity.org/admin/bims/downloadrequest/496/change/

**Comment by jeremyshelton** [comment]
@dimasciput @Fanevanjanahary - oh ok sorry.
This is just a download of app anuran data from the live site. 
Default settings - no filters applied.

**Comment by Fanevanjanahary** [comment]
Thank you @jeremyshelton @dimasciput

**Comment by jeremyshelton** [comment]
Hi @Fanevanjanahary 
Thank you for your work on this ticket.
Have checked **issue 1** and that looks good now 👍
For **issue 2**, the upstream ID column looks good 👍

What still needs to be addressed:

**1. The following 9 columns are very important and must appear in the CSV download for GBIF data, but currently these columns are blank for fish, anurans and other modules**
taxonKey
speciesKey
basisOfRecord
institutionCode
collectionCode
catalogNumber
identifiedBy
rightsHolder
recordedBy

Also, "Dataset Key" Should be replaced with "Taxon Key", and these columns should also 

<img width="831" alt="Screenshot 2022-08-02 at 09 47 47" src="https://user-images.githubusercontent.com/44292029/182323991-180a7cea-6de5-4875-b2e4-b9c1f9339238.png">

Here is a fish csv download showing these issues: 
[5955ea74d49ee23949025657d3f47d11ea23494fa00cafcc310edf1818d0a86b.csv](https://github.com/kartoza/django-bims/files/9240224/5955ea74d49ee23949025657d3f47d11ea23494fa00cafcc310edf1818d0a86b.csv)


**2. Anuran CSV issues**
The data populating the columns to the right of "AFDM-B" are incorrect: For example, Row 1 has a BDI link for a GBIF record? Also, all records should have the "Water Dependance" column populated, however this is not the case? Below is an example of an Anuran CSV file showing these issues.

[d1abe2591ddea6d9b90a0bc5cb711ada3d012562922fda1fa63dad1a7768c9fb.csv](https://github.com/kartoza/django-bims/files/9240213/d1abe2591ddea6d9b90a0bc5cb711ada3d012562922fda1fa63dad1a7768c9fb.csv)


@dimasciput @helendallas @timlinux

**Comment by dimasciput** [comment]
@jeremyshelton 

> taxonKey
> speciesKey
> basisOfRecord
> institutionCode
> collectionCode
> catalogNumber
> identifiedBy
> rightsHolder
> recordedBy

We don't have these data in our system since it's not in our original requirement, when we fetch occurrence from gbif data we only store the required data for FBIS and also the upstream id. If we want to have these data I have to create a script to fetch these and running the script in the background, and it might take a while to updates all existing gbif occurrences. 

Let me know if you want to continue. I think upstream id is enough because you can use it to see more detailed information in gbif.

> The five columns to the left of "Source" should also be populated:
> 
> Year = year column on GBIF
> Authors = "recorded by" column on GBIF
> Analyst institute = "institutionCode" on GBIF
> Analyst = "identifiedBy" on GBIF
> Collector/owner institute = "rightsHolder" on Gbif

This is a new feature request and not a bug. Please file a new feature request ticket for this, and I will size it. And these data not always available in gbif.

**Comment by dimasciput** [comment]
@helendallas

**Comment by dimasciput** [comment]
@jeremyshelton let me create the script anyway.

**Comment by jeremyshelton** [comment]
@dimasciput this is not a new request - please see ticket #2737 (from August last year), which requested the below fields to be added to the CSV downloads for GBIF data:

taxonKey
speciesKey
basisOfRecord
institutionCode
collectionCode
catalogNumber
identifiedBy
rightsHolder
recordedBy

The problem with pulling only the GBIF ID into our CSV is that we cannot easily search for those records on GBIF. I cannot find a way to easily search for a record by its GBIF id in GBIF. More importantly, we sometimes need the above fields for datasets comprising thousands of records - so querying individual GBIF IDs will not work for that situation (I se no way to query multiple GBIF IDs at a time on GBIF).

So can we please proceed with this script asap?

Just to be clear - this should be standard across all biodiversity modules.

@helendallas

**Comment by jeremyshelton** [comment]
For the below request, I will speak to @helendallas and revert.

_The five columns to the left of "Source" should also be populated:

Year = year column on GBIF
Authors = "recorded by" column on GBIF
Analyst institute = "institutionCode" on GBIF
Analyst = "identifiedBy" on GBIF
Collector/owner institute = "rightsHolder" on Gbif
This is a new feature request and not a bug. Please file a new feature request ticket for this, and I will size it. And these data not always available in gbif._

**Comment by dimasciput** [comment]
![image](https://user-images.githubusercontent.com/1979569/182532251-a6ac1705-c344-4da1-8f26-4b7adea8898f.png)

@jeremyshelton I've created a script and it's running at the moment, there's 130k gbif of data, it should be done tomorrow.

**Comment by jeremyshelton** [comment]
@dimasciput that's fantastic!
This is going to make a big difference. 
Thanks for your efficiency on this. 
Look forward to testing tomorrow.

**Comment by dimasciput** [comment]
@jeremyshelton 
> The data populating the columns to the right of "AFDM-B" are incorrect: For example, Row 1 has a BDI link for a GBIF record?

BDI Link and Water Dependance is an extra attribute of taxon data, so it won't check whether the occurrence is from gbif or virtual museum because they are different table. 
https://github.com/kartoza/django-bims/issues/2480

**Comment by jeremyshelton** [comment]
@dimasciput has there been any further progress on this ticket?
I am struggling to download csvs from live and testing sites, so currently unable to check...

**Comment by dimasciput** [comment]
@jeremyshelton will check again tomorrow, can you share the link you use to download the csv. Thanks

**Comment by jeremyshelton** [comment]
@dimasciput It was when I combined two filters that the downloads are not working (for example spatial filter + data source).

Dave you deployed your script yet? I see that the GBIF column data are still not coming through in csv downloads...?

**Comment by dimasciput** [comment]
@jeremyshelton I just checked and the gbif data are showing up now in the csv.

**Comment by dimasciput** [comment]
@jeremyshelton I only updated the gbif data in live site.

**Comment by jeremyshelton** [comment]
Thanks @dimasciput - I had a look at your download and the columns look good.

Thank you 👍

I am still waiting for some download requests to make sure it is working on all modules - the downloads do seem to be taking quite a long time to become available?

**Comment by dimasciput** [comment]
@jeremyshelton let me check it later, or probably over the weekend.

**Comment by jeremyshelton** [comment]
OK thanks @dimasciput
Let me know when the downloads are working more smoothly. 
Then I will test for each module and we can close the ticket 👍

**Comment by dimasciput** [comment]
@jeremyshelton this is now fixed, please give it a test.

**Comment by jeremyshelton** [comment]
OK thanks @dimasciput - testing now.

**Comment by jeremyshelton** [comment]
@dimasciput I am still struggling to download larger data sets.
For example this one: https://freshwaterbiodiversity.org/map/#site-detail/taxon=&search=&siteId=&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=[]&modules=1&validated=&sourceCollection=[%22fbis%22,%22gbif%22,%22virtual_museum%22]&abioticData=&ecologicalCategory=&rank=&siteIdOpen=&orderBy=name&polygon=&thermalModule=&dst=[%22DFFE%20Screening%20Tool%202022%22]

**Comment by jeremyshelton** [comment]
@dimasciput this csv download is still not working:
https://freshwaterbiodiversity.org/map/#site-detail/taxon=&search=&siteId=&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=[]&modules=1&validated=&sourceCollection=[%22fbis%22,%22gbif%22,%22virtual_museum%22]&abioticData=&ecologicalCategory=&rank=&siteIdOpen=&orderBy=name&polygon=&thermalModule=&dst=[%22DFFE%20Screening%20Tool%202022%22]

**Comment by dimasciput** [comment]
@jeremyshelton please test on testing

**Comment by jeremyshelton** [comment]
This is working nicely now on the live site.
Thank you @dimasciput 
Closing ticket.
