### ISSUE TITLE
Duplicate sites - again

### ISSUE THREAD

**Issue by helendallas** [kartoza/django-bims#3492]
Any idea why we have 2 or 3 sites with same codes, they all have site visits but only one has occurrence records. They are not thermal sites.
 
https://freshwaterbiodiversity.org/map/#search/A6NYLR-00002/taxon=&search=A6NYLR-00002&siteId=&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=[]&modules=&validated=&sourceCollection=[%22fbis%22,%22gbif%22,%22virtual_museum%22]&module=occurrence&ecologicalCategory=&rank=&siteIdOpen=&orderBy=name&polygon=&dst=&ecosystemType=
 
 
and
https://freshwaterbiodiversity.org/map/#site/siteIdOpen=86323
 
something has gone wrong again ☹

**Comment by dimasciput** [comment]
This is fixed on testing.

**Comment by helendallas** [comment]
So to confirm if a site had different co-ordinates you gave it a distinct FBSI Site Code?

**Comment by helendallas** [comment]
Thanks @dimasciput Please deploy to production

**Comment by helendallas** [comment]
Checking that this hasn't been deployed to production yet @dimasciput as issue still there

**Comment by dimasciput** [comment]
@helendallas I have deployed the fix to production, please test it again

**Comment by helendallas** [comment]
One site is strangely coded. I think when a river has 3 letters it gets stuck

https://freshwaterbiodiversity.org/location-site-form/update/?id=86324

**Comment by helendallas** [comment]
@dimasciput I have manually fixed this. Closing ticket now
